### PR TITLE
Ecto prefix support

### LINKED ISSUE #43: Support ecto prefixes
The prefixes should change the database, once it's possible from the driver.

### PR DESCRIPTION
**Pull request by rhetzler**
- Update Normalized Query to put database string where it will successfully pass through to Connection
- Update Mongo.Ecto ddl methods to pass prefix into NQ generation or directly to driver

- Should Fix #43  for 2.1 branch

### CODE REVIEW

**Comment by ankhers** [comment]
I'm not sure if it is just because we have certain tests disabled, but would you please be able to add a test for this?

**Comment by rhetzler** [comment]
You're right this needs tests. Will try to get to this soon, i've been pulled on to other things since.

**Comment by ankhers** [comment]
Any movement on this?

**Comment by ankhers** [comment]
Closing due to inactivity. If you would still like this, please reopen this PR and rebase from master.

**Pull request closed without merging**
