### PR TITLE
[WIP] Ecto 2 compatibility

### PR DESCRIPTION
**Pull request by michalmuskala**
This updates driver to the new db_connection based version and ecto to 2.0.

### CODE REVIEW

**Comment by agusguerra10** [comment]
Hey Michal, any news about this upgrade? I'm trying to use scrivener_ecto package but it requires Ecto 2.0. Thanks!

**Comment by Morganjackson** [comment]
@michalmuskala is this still in the works?  I don't know how much work is involved to finish this but I would be happy to kick in $200 if it helps. 

Looks like there are a few people wanting this so maybe we could setup something like [patreon](https://www.patreon.com/)?

**Comment by Fudoshiki** [comment]
+1

**Comment by ankhers** [comment]
For anyone that is waiting for this. Please look at #91. I am actively working on it.

**Comment by mbenatti** [comment]
Any news about this migration?

**Comment by auser** [comment]
Adding to my question too. Any updates?

**Comment by michalmuskala** [comment]
As mentioned above, the work continues in a separate PR https://github.com/michalmuskala/mongodb_ecto/pull/91

Unfortunately, updating this project is not a priority for me at the moment because of other obligations. If anybody would like to see this happen, I strongly encourage you to give @ankhers a hand and help with his PR.

**Comment by johnnyshields** [comment]
Please close this PR

**Comment by rsilvestre** [comment]
Hello, stupid question, but when do you think it's going to be fixed?

Regards,

**Comment by ankhers** [comment]
@rsilvestre This is already in a good place. Myself and others are already using it in production. All you need to do is point your dependency to this repo and branch. Something along the lines of

```elixir
{:mongodb_ecto, github: "michalmuskala/mongodb_ecto", branch: "ecto-2"}
```

That should get you started.

I believe the reason there has not been an actual release yet is because we are still touching up documentation, and there are a couple fixes that need to be applied to `ecto`. Unfortunately, I am unsure on the timeframe of an actual release. If you, or anyone else for that matter, would like to be notified of a release, make sure you are subscribed to this PR and you will get a notification when it is merged.

**Comment by johnnyshields** [comment]
Hi @ankhers is there a list of fixes which we're waiting on to be applied to Ecto?

**Comment by ankhers** [comment]
@johnnyshields Unfortunately I do not have that list. @michalmuskala would have a better idea of the changes that are required.

**Comment by ankhers** [comment]
I am going to close this in favour of the 2.1 branch release.

**Pull request closed without merging**
