### PR TITLE
fixes #130 warnings for rollbacks/transactions

### LINKED ISSUE #130: [ecto-2] Unit tests complaining about in_transaction and rollback missing
on branch `ecto-2`

```
Running tests...
warning: function Mongo.Ecto.in_transaction?/1 is undefined or private
  lib/eltoroportal/repo.ex:2

warning: function Mongo.Ecto.rollback/2 is undefined or private
  lib/eltoroportal/repo.ex:2
```

### PR DESCRIPTION
**Pull request by zeroasterisk**

### CODE REVIEW

**Comment by michalmuskala** [comment]
I'm pretty sure this is going to break stuff even more - ecto will assume transactional semantics if the `transaction` function is exported by the adapter.

**Comment by zeroasterisk** [comment]
oh?  yeah - that makes sense, I suppose...  I'll let you know if I run into problems...

**Comment by ankhers** [comment]
Closing because of no communication.

**Comment by zeroasterisk** [comment]
FYI - I was running this on my project for a while, without issues, but I don't really know how to test further.

**Comment by ankhers** [comment]
According to @michalmuskala, Ecto will try to call transactions in a couple different places. One example would be nested changesets. Unfortunately we cannot risk breaking the adapter to remove a couple compiler warnings. Maybe there is something that can be done about this later.

**Comment by ankhers** [comment]
And as it turns out, Ecto has already fixed this behaviour in 2.1.

**Pull request closed without merging**
