### PR TITLE
Update left side of `update_all` to an unused count

### PR DESCRIPTION
**Pull request by JamieREvans**
Left side of `update_all/3` is a count, not a tuple.

### CODE REVIEW

**Comment by JamieREvans** [comment]
Looks like these tests have been failing for a little while.

**Comment by ankhers** [comment]
I would rather not assign to that unecessary variable. Would you mind taking that out and than I can merge?

**Comment by JamieREvans** [comment]
Sure can.

For context, I created the variable to be explicit on the expected return to avoid someone coming along in the future and making the same mistake. Since it's an unbound variable, it never actually receives the assign and when compiled, it's treated like a comment and stripped.

**Comment by ankhers** [comment]
Thank you!

**Pull request merged**
