### PR TITLE
[Ecto 2] Fix Logging 🚀

### PR DESCRIPTION
**Pull request by cjbell**
This PR adds logging fixes for Ecto 2.

To get this to work I used `ecto 2.0.x` as your previous branch of ecto `mongo_test_corrections` doesn't seem to exist anymore. We may want to put this on master, but we have more to fix for Ecto 2.1 (as you noted) so think it's worth starting with Ecto 2.0.

The log format is just as before, I just fixed it up for the new version.

Ticks off the Logging box in https://github.com/michalmuskala/mongodb_ecto/pull/91

### CODE REVIEW

**Comment by cjbell** [comment]
As a nice side note, I wrote this during the NYC Elixir Meetup project night with some help from @davidantaramian

**Comment by ankhers** [comment]
I deleted the branch because it was merged into master of the main ecto repository.

Unfortunately with the impending release of ecto 2.1, I am not interested in fixing this for ecto 2.0.

With that said, if you want to fix the conflicts in order to use ecto 2.1, I would happily merge this.

**Comment by cjbell** [comment]
@ankhers Understandable – these logging fixes _should_ apply just fine to 2.1 as well (nothing changed with that release with these) however I would add that it will be impossible to test these without first fixing the other issues with Ecto 2.1 (of which there are many).

My proposed strategy would be to get to a place where we can cut a release for Ecto 2.0.x and then look to move onto fixing for Ecto 2.1.x. That way at least this library will have support for individuals coming to Ecto 2.0 without going to Ecto 2.1.

**Comment by ankhers** [comment]
Alright. I think I can deal with that. I'm going to cut a new branch for ecto 2.1 compatibility with the few changes I have already made. I will revert this branch (`ecto-2`) to the last known working state before I started updating libraries.

**Comment by ankhers** [comment]
@cjbell Can you please fix the merge conflicts? The version that you have ecto pinned to will include 2.1.x, which we do not want right now.

**Comment by cjbell** [comment]
Sure. Will update now.

**Comment by ankhers** [comment]
Thanks for the fix!

**Comment by cjbell** [comment]
Ah weirdly I think the revert on your branch has crept into this.... Did you want me to revert this and I can fix that?

**Comment by ankhers** [comment]
No, I think this is right. This is the branch that is mean to be used for the ecto 2.0 compatibility. I created a separate `ecto-2.1` for when work towards ecto 2.1 starts.

**Comment by ankhers** [comment]
Unless you mean the logging is no longer working?

**Comment by cjbell** [comment]
No no, logging is definitely still working!

**Comment by cjbell** [comment]
I think the git history just got a bit messed up because I merged your upstream branch where you had reverted some commits but I think it's in a good place regardless.

**Pull request merged**
