### PR TITLE
Need for `or_where`

### PR DESCRIPTION
**Pull request by mthomps4**
Looking to solve the issue for implementing `or_where`
I have written a few failing tests with `or_where`. 
Will look to solve. 

Using this PR as an open form of communication in the interim. 

`or_where` seems to fail when reducing inside normalize query -- `merge_keys`
> normalized_query.ex :336 

```
stacktrace:
       (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:448: Mongo.Ecto.NormalizedQuery.error/2
       (elixir) lib/map.ex:495: Map.update/4
       (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
       (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:232: Mongo.Ecto.NormalizedQuery.query/3
       (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:50: Mongo.Ecto.NormalizedQuery.all/2
       (mongodb_ecto) lib/mongo_ecto.ex:570: Mongo.Ecto.execute/6
       (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
       test/mongo_ecto_test.exs:81: (test)
```

### CODE REVIEW

**Comment by mthomps4** [comment]
Writing a test inside normalized_query_new_test for `or_where`
I'm not 100% on what the expected format should be.
the Mongo syntax would be something like `$or: [ { quantity: { $lt: 20 } }, { price: 10 } ]`

```
  test "or_where" do
    query = Schema |> or_where([r], r.x == 42) |> or_where([r], r.y != 43)
                   |> select([r], r.x) |> normalize
    assert_fields query, query: %{"$or": [ [y: ["$ne": 43]], [x: 42]]}

    query = Schema |> or_where([r], r.x == 5) |> or_where([r], r.x == 10) |> normalize
    assert_fields query, query: %{"$or": [ [x: 5], [x: 10] ] }
  end
```

**Comment by ankhers** [comment]
Make sure you write a test for a single `or_where` as well. It shouldn't end up having an `"$or"` in it at all.

**Comment by ankhers** [comment]
Is there any update on this?

**Comment by ankhers** [comment]
closing due to inactivity. Please feel free to re-open this and rebase off master.

**Pull request closed without merging**
